"""Build a sample WorkflowSpec into n8n JSON and optionally deploy it."""

from __future__ import annotations

import json
import sys

from agents.builder_agent import build_n8n_workflow
from agents.deployer_agent import N8nDeployError, deploy_workflow
from config import N8N_API_KEY, N8N_BASE_URL
from schemas.models import ActionSpec, TriggerSpec, WorkflowSpec


def main() -> int:
    spec = WorkflowSpec(
        name="WorkflowGPT Demo Ingest",
        description="Webhook payload forwarder generated by WorkflowGPT.",
        trigger=TriggerSpec(
            type="webhook",
            config={"method": "POST", "path": "workflowgpt-demo"},
        ),
        actions=[
            ActionSpec(
                type="http_request",
                config={
                    "id": "forward_payload",
                    "method": "POST",
                    "url": "https://httpbin.org/post",
                },
                depends_on=None,
            )
        ],
        raw_instruction=(
            "When a webhook is received, POST the payload to https://httpbin.org/post."
        ),
    )

    workflow_json = build_n8n_workflow(spec)
    print("Built n8n workflow JSON:")
    print(json.dumps(workflow_json, indent=2)[:2000])
    print("...")

    base_url = (N8N_BASE_URL or "http://localhost:5678").strip()
    api_key = (N8N_API_KEY or "").strip()
    if not api_key:
        print(
            "\nSkipping deploy: set N8N_API_KEY in workflowgpt/.env "
            f"(N8N_BASE_URL={base_url}).\n"
            "Create a key in n8n: Settings > n8n API > Create an API key."
        )
        return 0

    try:
        workflow_id = deploy_workflow(workflow_json, base_url, api_key)
    except N8nDeployError as exc:
        print(f"\nDeploy failed: {exc}", file=sys.stderr)
        return 1

    print(f"\nDeployed and activated workflow id: {workflow_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
